[global]
# Streamlit app settings
showSidebarContent = true
runOnSave = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[env]
GROQ_API_KEY = "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"
ENVIRONMENT = "production"
PROD_API_URL = "https://basic-lucille-100xengineers-9d02ce47.koyeb.app/" 